# -*- coding: utf-8 -*-
"""pdf2excel_plumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vfxUo0xdN0IFTAfD6lnnTDu9PwICAG5t
"""

!pip install pdfplumber

import pdfplumber
import re
import pandas as pd
import csv
fieldnames = ','.join(["TRNC_CODE", "TICKET_NUMBER", "ISSUE_DATE", "CPUI", "STAT", "FOP_CODE", "TRANS_AMOUNT", "FARE_AMOUNT", "TAX_AMT", "TAX_CODE", "TAX_FEES_CHARGES","PENALTY" ,"COBL_AMOUNT", "CORT", "COAM", "SPRT", "SPAM", "TAX_ON_COMMISSION", "BALANCE_PAYABLE"])
print ('hello')
line_items=[]
tkt_match_re = re.compile(r'^[A-Z +]{4} \d{10}')
#tkt_details_re = re.compile(r'^[A-Z +]{4} \d{10} (\d{2}[A-Z]{3}\d{2}) [A-Z]{4} [ ]{2} [A-Z]{1} [A-Z]{2} ([\d,]+\.\d{2}) ([\d,]+\.\d{2}) ([\d,]+\.\d{2}) [A-Z]{2} ([\d,]+\.\d{2})')
tkt_details_re = re.compile(r'[A-Z +]{4} \d{10}')

#file1 = open("/content/output/tmp_file_det.csv", "w")
with pdfplumber.open('/content/sample_data/AU_FCAIBILLDET_B_656_0502_AUD.PDF') as pdf:
  with open('/content/sample_data/output/tmp_file_det.csv', 'a', newline='') as outcsv:
          outcsv.write(fieldnames+'\n')
          page = pdf.pages
          for page in pdf.pages:
            text = page.extract_text()

            for line in text.split('\n'):
              if tkt_match_re.match(line):
                #print(line)
                #line_items.append(line)
                  line_comma = line.replace(',','')
                  outcsv.write(line_comma.replace(' ',',')+'\n')

        #print(line_items)
df = pd.read_csv(r'/content/sample_data/output/tmp_file_det.csv', sep=',')
        #print(df)
        #print(text)
df2 = df.drop(columns = ['CPUI','TAX_AMT','TAX_CODE'], axis=1)
df2.to_excel('/content/sample_data/output/au.xlsx')

